# Allow the end user to override certain values
substitutions:

  # Name
  name: "esphome"
  fullname: "ESPHome"

  # Board
  board: nodemcu-32s

  # Domain
  domain: .homelab.com

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${fullname}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: "espressify.${name}"
    version: "1.0"

# ESP32
esp32:
  board: ${board}
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

# Enable Over-The-Air updating
ota:
  password: !secret ota_password

# Enable WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ${domain}
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${fullname} Fallback Hotspot"
    password: !secret wifi_ap_password

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# Enable IPv6
network:
    enable_ipv6: true
